
export const quotes = [
  'Some are born great, some achieve greatness, and some have greatness thrust upon them.',
  'My words fly up, my thoughts remain below: Words without thoughts never to heaven go.',
  'Ignorance is the curse of God; knowledge is the wing wherewith we fly to heaven.',
  'God has given you one face, and you make yourself another.',
  'It is not in the stars to hold our destiny but in ourselves.',
  'We know what we are, but know not what we may be.',
  'A fool thinks himself to be wise, but a wise man knows himself to be a fool.',
  'All the world’s a stage, and all the men and women merely players: they have their exits and their entrances; and one man in his time plays many parts, his acts being seven ages.',
  'Good night, good night! Parting is such sweet sorrow, That I shall say good night till it be morrow.',
  'This above all: to thine own self be true, And it must follow, as the night the day,Thou canst not then be false to any man.',
  'If you prick us, do we not bleed? If you tickle us, do we not laugh? If you poison us, do we not die? And if you wrong us, shall we not revenge? The Merchant of Venice Act 3, Scene 1',
  'Better a witty fool than a foolish wit.',
  'False face must hide what the false heart doth know.',
  'It is a wise father that knows his own child.',
  'Listen to many, speak to a few.',
  'Action is eloquence.',
  'Uneasy lies the head that wears the crown.',
  'The robb’d that smiles, steals something from the thief.',
  'Suspicion always haunts the guilty mind.',
  'To do a great right do a little wrong.',
  'I am a man more sinned against than sinning.',
  'An overflow of good converts to bad.',
  'Is this a dagger which I see before me, the handle toward my hand?',
  'Beware the Ides of March.',
  'The better part of valor is discretion',
  'Words without thoughts never to heaven go.',
  'Brevity is the soul of wit.',
  'I would challenge you to a battle of wits, but I see you are unarmed!',
  'Frailty, thy name is woman.',
  'Nothing will come of nothing.',
  'Women may fall when there’s no strength in men.',
  'No legacy is so rich as honesty.',
  'What’s done can’t be undone.',
  'Some rise by sin, and some by virtue fall.',
  'Give every man thy ear, but few thy voice.',
  'Get thee to a nunnery.',
  'Hell is empty and all the devils are here.',
  'Things done well and with a care, exempt themselves from fear.',
  'To be, or not to be: that is the question',
  'The robbed that smiles, steals something from the thief.',
  'A peace is of the nature of a conquest; for then both parties nobly are subdued, and neither party loser.',
  'What light through yonder window breaks.',
  'How sharper than a serpent',
  'The lady doth protest too much, methinks',
  'Cry ‘havoc!’ and let slip the dogs of war',
  'Lord, what fools these mortals be!',
  'By all the vows that ever men have broke, in number more than ever women spoke',
  'All that glitters is not gold.',
  'This royal throne of kings, this sceptred isle… This blessed plot, this earth, this realm, this England.',
  'Our doubts are traitors and make us lose the good we often might win by fearing to attempt.',
  'There is nothing either good or bad, but thinking makes it so.',
  'Men at some time are masters of their fates: The fault, dear Brutus, is not in our stars, But in ourselves, that we are underlings.',
  'To thine own self be true, and it must follow, as the night the day, thou canst not then be false to any man.',
  'The wheel is come full circle: I am here.',
  'The evil that men do lives after them; The good is oft interrèd with their bones.',
  'We know what we are, but know not what we may be.',
  'There are more things in heaven and earth, Horatio, than are dreamt of in your philosophy.',
  'Full fathom five thy father lies, of his bones are coral made. Those are pearls that were his eyes. Nothing of him that doth fade, but doth suffer a sea-change into something rich and strange.',
  'The more pity that fools may not speak wisely what wise men do foolishly.',
  'Love is not love that alters when it alteration finds.',
  'Self-love, my liege, is not so vile a sin, as self-neglecting.',
  'Love is a smoke made with the fume of sighs.',
  'Love all, trust a few, do wrong to none.',
  'Love to faults is always blind, always is to joy inclined. Lawless, winged, and unconfined, and breaks all chains from every mind.',
  'If music be the food of love play on.',
  'The course of true love never did run smooth.',
  'Young men’s love then lies not truly in their hearts, but in their eyes.',
  'Love sought is good, but given unsought, is better.',
  'They have been at a great feast of languages, and stol’n the scraps.',
  'What’s in a name? That which we call a rose By any other word would smell as sweet…',
  'Who could refrain that had a heart to love and in that heart courage to make love known.',
  'Love looks not with the eyes, but with the mind; and therefore is winged Cupid painted blind.',
  'As soon go kindle fire with snow, as seek to quench the fire of love with words.',
  'I am one who loved not wisely but too well.',
  'I do love nothing in the world so well as you: is not that strange?',
  'They do not love that do not show their love.',
  'Some Cupid kills with arrows, some with traps.',
  'When a father gives to his son, both laugh; when a son gives to his father, both cry.',
  'Romeo, Romeo! wherefore art thou Romeo?',
  'Let me not to the marriage of true minds admit impediments.',
  'And this, our life, exempt from public haunt, finds tongues in trees, books in the running brooks, sermons in stones, and good in everything.',
  'The empty vessel makes the loudest sound.Life is as tedious as twice-told tale, vexing the dull ear of a drowsy man.',
  'We are such stuff as dreams are made on, and our little life is rounded with a sleep.',
  'Life',
  'But, for my own part, it was Greek to me.',
  'We have seen better days.',
  'A horse! a horse! my kingdom for a horse!',
  'Better three hours too soon than a minute too late.',
  'I cannot tell what the dickens his name is.',
  'I would give all my fame for a pot of ale, and safety.',
  'When we are born we cry that we are come to this great stage of fools.',
  'But where there is true friendship, there needs none.',
  'The band that seems to tie their friendship together will be the very strangler of their amity.',
  'I count myself in nothing else so happy / As in a soul remembering my good friends.',
  'To me, fair friend, you never can be old.',
  'Most friendship is feigning, most loving is folly.',
  'Neither a borrower nor a lender be; for loan oft loses both itself and friend, and borrowing dulls the edge of husbandry.',
  'Friendship is constant in all other things / Save in the office and affairs of love.',
  'Thy friendship makes us fresh.',
  'Friends, Romans, countrymen, lend me your ears: I come to bury Caesar, not to praise him.',
  'Keep thy friend / Under thy own life’s key..',
  'There is flattery in friendship.',
  'That which I would discover / The law of friendship bids me to conceal.',
  'Cowards die many times before their deaths; the valiant never taste of death but once.',
  'If you prick us, do we not bleed? If you tickle us, do we not laugh? If you poison us, do we not die? And if you wrong us, shall we not revenge?',
  'A man can die but once.',
  'Moderate lamentation is the right of the dead, excessive grief the enemy to the living.',
  'I burn, I pine, I perish.',
  'Off with his head!',
  'Come what come may, time and the hour runs through the roughest day.',
  'Time shall unfold what plighted cunning hides: Who cover faults, at last shame them derides.',
  'All the world ‘s a stage, and all the men and women merely players. They have their exits and their entrances; And one man in his time plays many parts.',
  'Shall I compare thee to a summer’s day?',
  'This is very midsummer madness.',
  'Now is the winter of our discontent',
  'Be not afraid of greatness. Some are born great, some achieve greatness, and others have greatness thrust upon them.',
  'The golden age is before us, not behind us.',
  'How poor are they that have not patience! What wound did ever heal but by degrees.',
  'The miserable have no other medicine, but only hope.',
  'To me, fair friend, you never can be old, For as you were when first your eye I ey’d, Such seems your beauty still.',
  'Beauty is bought by judgement of the eye.',
  'If I could write the beauty of your eyes And in fresh numbers number all your graces, The age to come would say, ‘This poet lies; Such heavenly touches ne’er touch’d earthly faces.’',
  'See how she leans her cheek upon her hand. O, that I were a glove upon that hand That I might touch that cheek!',
  'Beauty lives with kindness.',
  'She’s beautiful, and therefore to be wooed; She is a woman, therefore to be won.',
  'What a piece of work is a man, how noble in reason, how infinite in faculties, in form and moving how express and admirable, in action how like an angel, in apprehension how like a god.',
  'For where is any author in the world Teaches such beauty as a woman’s eye?',
  'Beauty itself doth of itself persuade the eyes of men without an orator.',
  'Beauty is but a vain and doubtful good; a shining gloss that fadeth suddenly; a flower that dies when it begins to bud; a doubtful good, a gloss, a glass, a flower, lost, faded, broken, dead within an hour.',
  'Beauty’s a doubtful good, a glass, a flower, Lost, faded, broken, dead within an hour; And beauty, blemish’d once, for ever’s lost, In spite of physic, painting, pain, and cost.',
  'Were beauty under twenty locks kept fast, yet love breaks through and picks them all at last.',
  'The most peerless piece of earth, I think, that e’ er the sun shone bright on.',
  'Tis beauty truly blent, whose red and white Nature’s own sweet and cunning hand laid on.',
  'Look on beauty, And you shall see ’tis purchased by the weight, Which therein works a miracle in nature, Making them lightest that wear most of it.',
  'Virtue is beauty, but the beauteous evil. Are empty trunks o’erflourished by the devil.',
  'Let witchcraft join with beauty, lust with both!',
  'All that glisters is not gold.'
].map(text => ({ text }));

